name: d7
recipe: drupal7
config:
  php: '7.4'
  composer_version: '2.1.9'
  via: apache:2.4
  webroot: web
  database: mysql:5.7
  drush: ^8
  xdebug: true
services:
  database:
    type: mysql:5.7
    run_as_root:
      # Creates the extra databases as root since the app user does not have those privileges
      - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS cg_game; GRANT ALL PRIVILEGES ON cg_game.* TO 'drupal7'@'%' IDENTIFIED by 'drupal7';"
      - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS detroit_game; GRANT ALL PRIVILEGES ON detroit_game.* TO 'drupal7'@'%' IDENTIFIED by 'drupal7';"
      - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS uslce_game; GRANT ALL PRIVILEGES ON uslce_game.* TO 'drupal7'@'%' IDENTIFIED by 'drupal7';"
      - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS wonderland_game; GRANT ALL PRIVILEGES ON wonderland_game.* TO 'drupal7'@'%' IDENTIFIED by 'drupal7';"
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
